import React from 'react';
import { Lightbulb, Clock, MapPin } from 'lucide-react';
import { DailyTip } from '../types';

interface DailyTipsProps {
  tips: DailyTip[];
}

export const DailyTips: React.FC<DailyTipsProps> = ({ tips }) => {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
      <div className="flex items-center space-x-2 mb-4">
        <Lightbulb className="h-5 w-5 text-yellow-500" />
        <h3 className="text-lg font-semibold text-gray-900">Today's Smart Tips</h3>
      </div>

      <div className="space-y-4">
        {tips.map((tip) => (
          <div key={tip.id} className="border-l-4 border-blue-500 pl-4 py-2">
            <div className="flex items-center space-x-2 mb-1">
              <span className="text-xs font-medium text-blue-600 bg-blue-50 px-2 py-1 rounded">
                {tip.category}
              </span>
              <div className="flex items-center space-x-1 text-xs text-gray-500">
                <Clock className="h-3 w-3" />
                <span>{tip.timestamp.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</span>
              </div>
            </div>
            <p className="text-gray-700 mb-2">{tip.content}</p>
            {tip.relevantLocations.length > 0 && (
              <div className="flex items-center space-x-1 text-xs text-gray-500">
                <MapPin className="h-3 w-3" />
                <span>Related locations available</span>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-4 pt-4 border-t border-gray-100">
        <p className="text-xs text-gray-500 text-center">
          Tips generated by AI based on campus activity and your preferences
        </p>
      </div>
    </div>
  );
};